### ISSUE TITLE
How to use make bench

### ISSUE THREAD

**Issue by ghost** [charlesportwoodii/php-argon2-ext#8]
I read the documentation and it said to run a make bench test. I did that and it spit out a binary file. How am I supposed to determine the appropriate settings from that file?

**Comment by charlesportwoodii** [comment]
Read chapter 9 of the spec https://password-hashing.net/argon2-specs.pdf.

You want to find the best values for your system that you can tolerate. The default values are both sane and secure. You only need to tweak them if you want longer hash times.

Separately, if you want password hashing, use the PHP 7.2 built ins `password_hash`. If you need more Argon2 functionality look at libsodium instead of this library, as it supercedes all functionality of this library, and is pre-bundled in PHP 7.2.
